# Generated by Django 5.2.1 on 2025-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0004_attendancelog_hours_alter_employeeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='hours',
            field=models.FloatField(default=0),
        ),
    ]
