# Generated by Django 5.2.1 on 2025-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0005_alter_attendancelog_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='event',
            field=models.CharField(choices=[('start', 'Начало работы'), ('break', 'Перерыв'), ('resume', 'Продолжение работы'), ('end', 'Окончание работы')], max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='overtime_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
